# Database Settings
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 5
        session_factory:
          statement_inspector: com.example.study.hibernate.interceptor.SQLTrackingStatementInspector


# basic log level for all messages

management:
  endpoints:
    web:
      exposure:
        include: "*"