# Database Settings
spring:
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/mongodb-container?authSource=admin


management:
  endpoints:
    web:
      exposure:
        include: "*"


