management:
  health:
    db:
      enabled: false
    redis:
      enabled: false
  endpoint:
    env:
      show-values: ALWAYS
    shutdown:

  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
#    health:
#      show-details: always

very:
  important:
    password: top-secret

# Database Settings
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/your_database_name
#    username: your_postgres_username
#    password: your_postgres_password
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
