version: '3.8'
services:
  postgresql:
    image: postgres:14.6
    # volumes:
    #   - ~/volumes/jhipster/jhip_api_first/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=psltest
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
    command: [ "postgres", "-c", "max_connections=1000", "-c", "max_prepared_transactions=100" ]
