server:
  port: 8080

spring:
  profiles:
    active: local

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      enable-auto-commit: true
#    listener:
#      ack-mode: manual


---

spring:
  profiles:
    active: dev

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      enable-auto-commit: true
#    listener:
#      ack-mode: manual

