server:
  port: 8081
  shutdown: graceful

spring:
  profiles:
    active: local

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      properties:
        max.poll.interval.ms: 10000
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      enable-auto-commit: false
      max-poll-records: 100

    listener:
      ack-mode: manual
      immediate-stop: false
  lifecycle:
    timeout-per-shutdown-phase: 60s



---
spring:
  profiles:
    active: dev

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      enable-auto-commit: false
      max-poll-records: 100
    listener:
      ack-mode: manual
      immediate-stop: true

