version: '3.8'
services:
  mysql:
    image: mysql:8.0.22
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
