server:
  port: 8081

# Database Settings
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# basic log level for all messages
logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: debug
    org.hibernate.SQL_SLOW: info
    org.hibernate.cache: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"


